[build]
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/out"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"